#!/bin/bash

export TYPEORM_DRIVER_TYPE=$TYPEORM_DRIVER_TYPE
export TYPEORM_HOST=$TYPEORM_HOST
export TYPEORM_PORT=$TYPEORM_PORT
export TYPEORM_AUTO_SCHEMA_SYNC=$TYPEORM_AUTO_SCHEMA_SYNC

export TYPEORM_DATABASE=$MYSQL_DATABASE
export TYPEORM_USERNAME=$MYSQL_USER
export TYPEORM_PASSWORD=$MYSQL_PASSWORD
